Repository larq/larq, pull requests merged in 2019-09, with the labels that each got.

#196 Cleanup Home page and add logo to readme
  README.md
  docs/images/logo.svg
  docs/index.md
  mkdocs.yml
Labels: documentation

#199 Move larq_zoo docs to main repo
  .gitignore
  apidocs.yml
  docs/models/examples.md
  docs/models/index.md
  docs/plots/binary_alexnet.vg.json
  docs/plots/birealnet.vg.json
  docs/plots/densenet_28.vg.json
  docs/plots/densenet_37.vg.json
  docs/plots/densenet_45.vg.json
  docs/plots/resnet_e_18.vg.json
  docs/plots/xnornet.vg.json
  generate_api_docs.py
  larqdocs.sh
  mkdocs.yml
  setup.py
Labels: documentation

#201 Cleanup front page
  docs/index.md
Labels: documentation

#202 Update Larq Zoo docs to the latest version
  apidocs.yml
  docs/models/index.md
  docs/plots/binary_alexnet.vg.json
  docs/plots/birealnet.vg.json
  docs/plots/densenet_28.vg.json
  docs/plots/densenet_37.vg.json
  docs/plots/densenet_37_dilated.vg.json
  docs/plots/densenet_45.vg.json
  docs/plots/resnet_e_18.vg.json
  docs/plots/xnornet.vg.json
  setup.py
Labels: documentation

#200 Add docs formatter to automatically add netron links
  mkdocs.yml
  netron_link.py
Labels: documentation

#204 Switch hosting from GitHub Pages to Zeit Now
  CONTRIBUTING.md
  azure-pipelines.yml
  build.sh
  larqdocs.sh
  now.json
  plot_activation.py
Labels: documentation

#205 Unify colour scheme and fix some minor styling issues
  docs-theme/partials/nav.html
  docs-theme/partials/palette.html
  docs/custom.css
  docs/examples/binarynet_advanced_cifar10.ipynb
  docs/examples/binarynet_cifar10.ipynb
  docs/examples/mnist.ipynb
  mkdocs.yml
Labels: documentation

#207 Fix class of tab bar to correctly reflow on mobile devices
  docs-theme/partials/header.html
Labels: documentation

#210 Fix Tensor comparison to support TF2-rc0 hashing behaviour
  azure-pipelines.yml
  larq/layers_base.py
  larq/metrics.py
  larq/models.py
Labels: bug

#216 Add TensorFlow 1.15.0-rc0 to test matrix
  azure-pipelines.yml
Labels: tests

#218 Bump MathJax@3 Vega-Embed@5
  mkdocs.yml
Labels: documentation

#221 Test against TensorFlow 2.0.0-rc1
  azure-pipelines.yml
Labels: tests

#219 Add meta tags to properly show up in social media
  docs-theme/main.html
  docs/images/social-preview.png
Labels: documentation

#217 Add JOSS publication
  paper/paper.bib
  paper/paper.md
Labels: documentation

#227 Spelling and Grammar suggestions (in addition to JOSS review)
  docs/about.md
  docs/faq.md
  docs/guides/bnn-architecture.md
  docs/guides/bnn-optimization.md
  docs/guides/key-concepts.md
  docs/index.md
  docs/models/index.md
  docs/papers.md
Labels: documentation

#228 Downgrade MathJax@2
  mkdocs.yml
Labels: documentation

#231 Use Altair/Vega to plot activations and quantizers in API docs
  .gitignore
  build.sh
  mkdocs.yml
  plot_activation.py
  plot_altair.py
  setup.py
Labels: documentation

#235 Switch Larq Zoo examples to a runnable notebook
  docs/index.md
  docs/models/examples.ipynb
  docs/models/examples.md
  mkdocs.yml
Labels: documentation

#237 Add note on how to reach out to us
  CONTRIBUTING.md
Labels: documentation

#236 Add missing binder dependencies
  requirements.txt
Labels: documentation

#238 Add link to tf.math.sign in lq.math.sign
  larq/math.py
Labels: documentation

#242 Add link to larq/zoo repo
  docs/models/index.md
Labels: documentation

#240 Clarify installation instructions
  README.md
  docs/index.md
Labels: documentation

#241 Mention students in about page
  docs/about.md
Labels: documentation

#239 Change "Why Larq?" menu item to "About"
  mkdocs.yml
Labels: documentation

#257 Add formula for swish sign and improve docs for magnitude aware sign
  larq/quantizers.py
Labels: documentation

#259 Mathematically clarify binarization in guide
  docs/guides/key-concepts.md
Labels: documentation

#258 Cite BNN NeurIPS paper
  docs/index.md
  mkdocs.yml
  paper/paper.bib
  paper/paper.md
Labels: documentation

#261 Extend example on front page and remove it from user guide
  docs/guides/key-concepts.md
  docs/index.md
Labels: documentation
