Repository larq/larq, pull requests merged in 2019-12, with the labels that each got.

#345 Fix typos in paper
  paper/paper.md
Labels: documentation

#351 Fix paper typo
  paper/paper.md
Labels: documentation

#352 Cite conference versions of the papers
  paper/paper.bib
Labels: documentation

#355 Cite NeurIPS paper instead of arXiv version
  docs/guides/bnn-optimization.md
  docs/papers.md
  larq/optimizers.py
Labels: documentation

#312 RFC: Quantized Variables
  larq/conftest.py
  larq/conftest_test.py
  larq/layers_base.py
  larq/models.py
  larq/quantized_scope.py
  larq/quantized_variable.py
  larq/quantized_variable_test.py
  larq/snapshots/snap_quantized_variable_test.py
  larq/testing_utils.py
  larq/utils.py
  setup.py
Labels: API, feature

#357 Simplify assign operations in Bop
  larq/optimizers.py
Labels: internal-improvement

#359 Use from_variable factory method to instantiate QuantizedVariables
  larq/layers_base.py
  larq/quantized_variable.py
  larq/quantized_variable_test.py
  setup.cfg
Labels: feature

#363 Change default hyperparameters of Bop
  larq/optimizers.py
Labels: breaking-change

#367 Update Bop documentation
  larq/optimizers.py
Labels: documentation
