Repository larq/larq, pull requests merged in 2019-11, with the labels that each got.

#308 Run unit tests in parallel using `pytest-xdist`
  .github/workflows/unittest.yml
  CONTRIBUTING.md
  setup.py
Labels: internal-improvement

#307 Upgrade MathJax@3
  docs/guides/bnn-optimization.md
  docs/guides/key-concepts.md
  larq/quantizers.py
  mkdocs.yml
Labels: dependencies

#310 Bump black
  .github/workflows/lint.yml
Labels: dependencies

#313 Add pytest fixture to run tests in eager and graph mode
  larq/conftest.py
  larq/conftest_test.py
  larq/metrics_test.py
  larq/quantizers_test.py
Labels: internal-improvement

#304 Refactor Bop into Bop + CaseOptimizer
  apidocs.yml
  larq/callbacks_test.py
  larq/optimizers.py
  larq/optimizers_test.py
  larq/optimizers_v2.py
Labels: breaking-change

#316 Fix log count check in layer warnings tests
  larq/layers_test.py
Labels: bug

#317 Drop TensorFlow 1.13
  .github/workflows/unittest.yml
  README.md
  apidocs.yml
  docs/index.md
  larq/layers_base.py
  larq/metrics.py
  larq/models_test.py
  larq/optimizers.py
  larq/optimizers_test.py
  larq/optimizers_v1.py
  larq/optimizers_v2.py
  larq/quantizers.py
  larq/testing_utils.py
  larq/utils.py
  setup.py
Labels: breaking-change

#318 Add link to NeurIPS poster
  docs/papers.md
Labels: documentation

#319 Refactor tests to not use TensorFlow TestCase
  larq/conftest.py
  larq/layers_test.py
  larq/testing_utils.py
  setup.py
Labels: internal-improvement

#320 Simplify layer tests
  larq/layers_test.py
Labels: internal-improvement

#321 Group and organize quantizer tests
  larq/quantizers_test.py
Labels: internal-improvement

#322 Quantizer layer tests
  larq/layers_test.py
  larq/quantizers_test.py
  larq/testing_utils.py
Labels: internal-improvement

#324 Bump version to 0.8.0
  setup.py
Labels: skip-changelog

#331 Fix examples in documentation for CaseOptimizer and Bop
  larq/optimizers.py
Labels: documentation

#332 Fix try except in model summary
  larq/models.py
Labels: bug

#334 Fix reloading of Bop when used with schedules
  larq/optimizers.py
  larq/optimizers_test.py
Labels: bug

#335 v0.8.1
  setup.py
Labels: skip-changelog

#329 Second paper draft
  paper/paper.bib
  paper/paper.md
Labels: documentation

#339 Test against TF 2.1rc0
  .github/workflows/unittest.yml
Labels: internal-improvement

#340 Fix reloading of case optimizer weights
  larq/layers_test.py
  larq/optimizers.py
  larq/optimizers_test.py
Labels: bug

#341 Bump version to 0.8.2
  setup.py
Labels: skip-changelog
