Repository larq/larq, pull requests merged in 2019-10, with the labels that each got.

#260 Extend site description
  mkdocs.yml
Labels: documentation

#271 Enforce PR labels
  .github/pr_labels.yml
Labels: internal improvement

#272 Add github action to publish package
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  CONTRIBUTING.md
  azure-pipelines.yml
Labels: internal improvement

#273 Automatically draft release notes
  .github/pr_labels.yml
  .github/release-drafter.yml
  CONTRIBUTING.md
Labels: documentation, internal-improvement

#274 Reorder quantizers so they show up grouped in the docs
  larq/quantizers.py
Labels: documentation

#275 Add Release Drafter as GH action
  .github/release-drafter.yml
  .github/workflows/release-notes.yml
Labels: internal-improvement

#276 Only run release notes action on pushed to master
  .github/release-drafter.yml
  .github/workflows/release-notes.yml
Labels: internal-improvement

#277 Run unit tests with GitHub actions
  .github/workflows/unittest.yml
  README.md
  azure-pipelines.yml
  codecov.yml
  larq/metrics.py
  larq/quantizers.py
  larq/quantizers_test.py
Labels: internal-improvement

#281 Add explanation of scoped metric definition
  larq/metrics.py
Labels: documentation

#285 Bump vega-embed@6
  mkdocs.yml
Labels: dependencies

#284 Quantizer tests improvements
  larq/quantizers_test.py
Labels: internal-improvement

#287 Fix iteration bug in Bop with TensorFlow 2.0.0
  larq/optimizers_test.py
  larq/optimizers_v2.py
  larq/testing_utils.py
Labels: bug

#289 Prepare for v0.7.4
  setup.py
Labels: skip-changelog

#288 Fix links on front page
  README.md
  docs/index.md
Labels: documentation

#290 Update Release Docs
  CONTRIBUTING.md
Labels: documentation

#291 Use animated logo in the README
  README.md
Labels: documentation

#292 Cleanup lq.math tests
  larq/activations_test.py
  larq/constraints_test.py
  larq/math_test.py
  larq/quantizers_test.py
  larq/testing_utils.py
Labels: internal-improvement

#293 Heaviside Function
  larq/math.py
  larq/math_test.py
  larq/quantizers.py
Labels: internal-improvement

#295 Add google analytics tracking
  mkdocs.yml
Labels: documentation

#303 Enhancements for CONTRIBUTING.md shell commands + adding editors to .gitignore
  .gitignore
  CONTRIBUTING.md
Labels: documentation

#302 Fix zero division bug in summary for weightless models
  larq/models.py
  larq/models_test.py
  larq/snapshots/snap_models_test.py
Labels: bug
