Repository larq/larq, pull requests merged in 2019-07, with the labels that each got.

#116 Fix twitter link and minify generated html pages to save a few kB
  mkdocs.yml
  setup.py
Labels: documentation

#125 Ignore weights from layer metrics in summary
  larq/models.py
Labels: bug

#128 Add snapshot tests for model summary to catch bugs like #125
  larq/models.py
  larq/models_test.py
  larq/snapshots/__init__.py
  larq/snapshots/snap_models_test.py
  setup.py
Labels: tests

#129 Fix Binder links for example notebooks
  docs/examples/binarynet_advanced_cifar10.ipynb
  docs/examples/binarynet_cifar10.ipynb
  docs/examples/mnist.ipynb
Labels: documentation

#130 fixed typo in SteTern dokumentation
  larq/quantizers.py
Labels: documentation

#131 Add links to notebooks on GitHub and improve buttons
  README.md
  docs/examples/binarynet_advanced_cifar10.ipynb
  docs/examples/binarynet_cifar10.ipynb
  docs/examples/mnist.ipynb
Labels: documentation

#134 Regenerate model summary in example notebooks
  docs/examples/binarynet_advanced_cifar10.ipynb
  docs/examples/binarynet_cifar10.ipynb
  docs/examples/mnist.ipynb
Labels: documentation

#138 First draft of guides, about, faq; relocation examples
  docs/about.md
  docs/architecture_guide.md
  docs/faq.md
  docs/guide.md
  docs/optimization_guide.md
  mkdocs.yml
Labels: documentation

#143 Fetch larq-zoo docs before running mkdocs
  .gitignore
  CONTRIBUTING.md
  azure-pipelines.yml
  larqdocs.sh
  mkdocs.yml
Labels: documentation

#146 Improved hyperlinks, plus docs on quantizers as activations
  docs/code-of-conduct.md
  docs/guides/bnn-architecture.md
  docs/guides/bnn-optimization.md
  docs/guides/key-concepts.md
  larq/quantizers.py
  mkdocs.yml
Labels: documentation

#152 Add interactive plot for building BNN guide
  docs/guides/bnn-architecture.md
  docs/plots/first_and_last_layers.vg.json
  mkdocs.yml
  plot_altair.py
Labels: documentation

#153 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#154 Include xnornet plots in documentation
  .gitignore
  larqdocs.sh
Labels: documentation

#158 Simplify CI config using pytest-azurepipelines
  azure-pipelines.yml
  larq/testing_utils.py
Labels: tests

#162 Add sticky tab navigation
  docs-theme/partials/header.html
  docs-theme/partials/tabs.html
  docs/custom.css
  mkdocs.yml
Labels: documentation

#164 Website: Fix box-shadow flickering
  docs/custom.css
Labels: documentation

#167 Fix RuntimeError: generator didn't yield
  larq/utils.py
Labels: bug
