Repository larq/larq, pull requests merged in 2020-01, with the labels that each got.

#371 Fix weight_clip documentation issue
  docs/guides/bnn-architecture.md
Labels: documentation

#370 Address paper review comments
  paper/paper.md
Labels: documentation

#376 Fix larq.dev deployment
  .gitignore
  build.sh
  now.json
  package.json
Labels: documentation

#374 Upgrade pytype
  setup.py
Labels: dependencies

#378 Test against TF 2.1.0
  .github/workflows/unittest.yml
Labels: internal-improvement

#380 Fix link to `Bop` in docs.
  docs/guides/bnn-optimization.md
Labels: documentation

#381 Fix bug in HyperParameterScheduler
  .gitignore
  larq/callbacks.py
  larq/callbacks_test.py
  larq/snapshots/snap_models_test.py
  larq/snapshots/snap_quantized_variable_test.py
Labels: bug

#382 Fix typo in case optimizer docs
  larq/optimizers.py
Labels: documentation

#383 Add missing DOIs to paper references
  paper/paper.bib
Labels: documentation

#384 Fix paper.bib
  paper/paper.bib
Labels: documentation

#386 Change dabnn citation to cite conference version
  paper/paper.bib
Labels: documentation

#389 Add DOI badge and update larq citation
  README.md
  docs/faq.md
Labels: documentation

#392 Fix typo in `DoReFa` docs.
  larq/quantizers.py
Labels: documentation

#391 (Partially) add type hints. See #309.
  larq/activations.py
  larq/callbacks.py
  larq/constraints.py
  larq/layers_base.py
  larq/models.py
  larq/models_test.py
  larq/optimizers.py
  larq/quantized_variable.py
  larq/quantized_variable_test.py
  larq/quantizers.py
  larq/utils.py
Labels: internal-improvement

#395 Remove gast from requirements.txt
  requirements.txt
Labels: internal-improvement

#387 RFC: Quantizers as subclasses of keras.layer.Layer
  .github/workflows/lint.yml
  docs/guides/bnn-architecture.md
  docs/guides/key-concepts.md
  larq/conftest.py
  larq/quantized_variable_test.py
  larq/quantizers.py
  larq/quantizers_test.py
  plot_altair.py
Labels: breaking-change

#385 Support per-step scheduling in HyperParameterScheduler
  larq/callbacks.py
  larq/callbacks_test.py
Labels: feature

#398 Fix optimizer reloading of CaseOptimizer with tf.train.Checkpoint
  larq/optimizers.py
  larq/optimizers_test.py
Labels: bug
