Repository larq/larq, pull requests merged in 2020-08, with the labels that each got.

#557 Run linting using Python 3.8 on CI
  .github/workflows/lint.yml
  setup.cfg
Labels: internal-improvement

#562 Change PyPI author email to opensource@plumerai.com
  setup.py
Labels: skip-changelog

#564 Emphasize importance of LCE in README.md
  README.md
Labels: documentation

#556 Fix distributed quantized variable assignment in TF 2.x
  larq/quantized_variable.py
  larq/quantized_variable_test.py
Labels: bug
