Repository larq/larq, pull requests merged in 2020-06, with the labels that each got.

#500 Apply Python Black formatting to docstring examples
  README.md
  larq/optimizers.py
  larq/quantizers.py
Labels: documentation

#501 Improve alignment of LaTeX formulas
  larq/math.py
Labels: documentation

#506 Cleanup tests
  larq/conftest.py
  larq/conftest_test.py
  larq/layers_test.py
  larq/metrics_test.py
  larq/optimizers_test.py
  larq/quantized_variable_test.py
  larq/quantizers_test.py
Labels: internal-improvement

#507 Run distribution strategy tests with multiple virtual CPUs
  larq/conftest.py
  larq/optimizers_test.py
  larq/quantized_variable_test.py
Labels: internal-improvement

#498 Add support for TensorFlow 2.3
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
  larq/quantized_variable.py
  larq/quantized_variable_test.py
Labels: feature

#513 Upgrade pytype to autoselect jobs on CI
  .github/workflows/lint.yml
  setup.py
Labels: dependencies
