Repository larq/larq, pull requests merged in 2020-03, with the labels that each got.

#444 Move memory string formatting into utils
  larq/__init__.py
  larq/models.py
  larq/models_test.py
  larq/utils.py
  larq/utils_test.py
Labels: internal-improvement

#442 Add NoOpQuantizer for use with Bop
  larq/optimizers.py
  larq/optimizers_test.py
  larq/quantizers.py
  larq/quantizers_test.py
Labels: breaking-change

#445 Add Larq meta info to README.md
  README.md
Labels: documentation

#447 Remove unnecessary # from format string
  larq/models.py
Labels: internal-improvement

#446 Case opt check
  larq/optimizers.py
  larq/optimizers_test.py
Labels: internal-improvement

#450 Consolidate context managers under lq.context
  larq/__init__.py
  larq/conftest.py
  larq/conftest_test.py
  larq/context.py
  larq/context_test.py
  larq/layers_base.py
  larq/layers_test.py
  larq/metrics.py
  larq/metrics_test.py
  larq/quantized_scope.py
  larq/quantized_variable.py
  larq/quantized_variable_test.py
  larq/quantizers.py
  larq/quantizers_test.py
Labels: breaking-change

#449 Model size for 8-bit quantized full-precision weights
  larq/models.py
  larq/models_test.py
  larq/snapshots/snap_models_test.py
Labels: feature

#453 Upgrade github actions
  .github/workflows/lint.yml
  .github/workflows/publish.yml
  .github/workflows/release-notes.yml
  .github/workflows/unittest.yml
Labels: dependencies

#452 Add quantized variable fixes from TF upstream
  larq/quantized_variable.py
Labels: bug

#451 Add CI job to test larq against TensorFlow 2.2rc0
  .github/workflows/unittest.yml
  larq/metrics_test.py
  larq/quantized_variable_test.py
Labels: internal-improvement

#455 Fix ordering of costring arguments scheduler
  larq/callbacks.py
Labels: documentation

#438 Add support for non-zero padding
  larq/layers.py
  larq/layers_base.py
  larq/layers_test.py
  larq/utils.py
  setup.py
Labels: feature

#456 Simplify release process
  .github/workflows/publish.yml
  CONTRIBUTING.md
Labels: internal-improvement

#457 Upgrade version number to 0.9
  setup.py
Labels: skip-changelog

#458 Fix deserialization of quantizer functions
  larq/quantizers.py
  larq/quantizers_test.py
Labels: bug

#459 Upgrade version number to 0.9.1
  setup.py
Labels: skip-changelog

#462 Update version number to 0.9.2
  setup.py
Labels: skip-changelog

#461 Support unknown input shapes with one padding
  larq/layers_base.py
  larq/layers_test.py
Labels: bug

#463 Use static tensor shapes if possible for one-padding
  larq/layers_base.py
  larq/layers_test.py
  larq/models_test.py
Labels: bug

#464 Update version number to 0.9.3
  setup.py
Labels: skip-changelog

#466 Add support for experimental_aggregate_gradients
  .github/workflows/unittest.yml
  larq/optimizers.py
  larq/optimizers_test.py
Labels: feature

#468 Make quantiser names consistent. Closes #467.
  larq/optimizers.py
  larq/optimizers_test.py
  larq/quantizers.py
  larq/quantizers_test.py
Labels: API, internal-improvement

#469 Add Python 3.8 to CI matrix
  .github/workflows/unittest.yml
Labels: internal-improvement
