Repository larq/larq, pull requests merged in 2020-02, with the labels that each got.

#404 Lazily build metrics
  larq/layers_base.py
  larq/metrics.py
  larq/metrics_test.py
Labels: internal-improvement

#418 Restructure docs and add compute-engine tab
  .gitignore
  README.md
  docs-theme/main.html
  docs-theme/partials/header.html
  docs-theme/partials/nav.html
  docs-theme/partials/tabs.html
  docs/about.md
  docs/code-of-conduct.md
  docs/contributing.md
  docs/custom.css
  docs/examples/binarynet_advanced_cifar10.ipynb
  docs/faq.md
  docs/images/favicon-32.png
  docs/images/logo-big-font.svg
  docs/images/logo.svg
  docs/images/social-preview.png
  docs/index.md
  docs/larq/guides/bnn-architecture.md
  docs/larq/guides/bnn-optimization.md
  docs/larq/guides/key-concepts.md
  docs/larq/tutorials/binarynet_cifar10.ipynb
  docs/larq/tutorials/mnist.ipynb
  docs/zoo/index.md
  docs/zoo/tutorials.ipynb
  download_lce_docs.sh
  generate_api_docs.py
  mkdocs.yml
  package.json
Labels: documentation

#423 Fix more links
  docs/faq.md
  docs/larq/tutorials/binarynet_cifar10.ipynb
  docs/larq/tutorials/mnist.ipynb
  docs/zoo/tutorials.ipynb
Labels: documentation

#424 Workaround #422
  docs/faq.md
Labels: documentation

#432 Remove outdated reference to tutorial from README, closes #431
  README.md
Labels: documentation

#430 Align the navbar icons.
  docs/custom.css
Labels: documentation

#433 Move docs to larq/docs
  .gitignore
  CONTRIBUTING.md
  README.md
  apidocs.yml
  docs-theme/main.html
  docs-theme/partials/header.html
  docs-theme/partials/nav.html
  docs-theme/partials/palette.html
  docs/CNAME
  docs/custom.css
  docs/faq.md
  docs/images/favicon-32.png
  docs/images/logo-big-font.svg
  docs/images/social-preview.png
  docs/index.md
  docs/larq/guides/bnn-architecture.md
  docs/larq/guides/bnn-optimization.md
  docs/larq/guides/key-concepts.md
  docs/larq/tutorials/binarynet_cifar10.ipynb
  docs/larq/tutorials/mnist.ipynb
  docs/papers.md
  docs/plots/binary_alexnet.vg.json
  docs/plots/birealnet.vg.json
  docs/plots/densenet_28.vg.json
  docs/plots/densenet_37.vg.json
  docs/plots/densenet_37_dilated.vg.json
  docs/plots/densenet_45.vg.json
  docs/plots/dorefanet.vg.json
  docs/plots/first_and_last_layers.vg.json
  docs/plots/resnet_e_18.vg.json
  docs/plots/xnornet.vg.json
  docs/zoo/index.md
  docs/zoo/tutorials.ipynb
  download_lce_docs.sh
  generate_api_docs.py
  mkdocs.yml
  netron_link.py
  now.json
  package.json
  plot_altair.py
  requirements.txt
  setup.py
Labels: documentation

#435 threshold description fix
  larq/optimizers.py
Labels: documentation

#402 Move custom metrics from layers to quantizers
  larq/layers.py
  larq/layers_base.py
  larq/layers_test.py
  larq/metrics.py
  larq/metrics_test.py
  larq/quantizers.py
  larq/quantizers_test.py
Labels: breaking-change

#436 Cleanup base layers
  larq/layers_base.py
  larq/models.py
Labels: internal-improvement

#437 Simplify quantizer metrics
  larq/layers_base.py
  larq/quantizers.py
Labels: internal-improvement
