Repository larq/larq, pull requests merged in 2020-05, with the labels that each got.

#485 Fix case optimizer when used with distributed mixed precision loss scaling
  larq/optimizers.py
Labels: bug

#486 Add TF 2.2.0 to CI test matrix
  .github/workflows/unittest.yml
  README.md
  setup.py
Labels: documentation

#482 Reformat docs for keras-autodoc
  larq/activations.py
  larq/callbacks.py
  larq/constraints.py
  larq/context.py
  larq/layers.py
  larq/math.py
  larq/metrics.py
  larq/models.py
  larq/optimizers.py
  larq/quantized_variable.py
  larq/quantizers.py
  larq/utils.py
Labels: documentation

#488 Update version to 0.9.5
  setup.py
Labels: skip-changelog

#490 Fix references for QuantConv3DTranspose
  larq/layers.py
Labels: documentation

#491 Correctly compute one-padding shape to prevent recreating conv_op
  larq/layers_base.py
  larq/layers_test.py
Labels: bug

#492 Don't lazily compute _is_native_padding
  larq/layers_base.py
Labels: bug

#493 :arrow_up: 0.9.6
  setup.py
Labels: skip-changelog

#494 Add warning to DoReFa docstring
  larq/quantizers.py
Labels: documentation

#497 Fix metric typo
  larq/metrics.py
  larq/metrics_test.py
Labels: bug
