Repository larq/larq, pull requests merged in 2021-05, with the labels that each got.

#651 Add DoReFa Weight Quantizer
  larq/quantizers.py
  larq/quantizers_test.py
Labels: feature

#660 Add DoReFa plot for `mode="weights"`
  larq/quantizers.py
Labels: documentation

#661 Document support for TF 2.5 and Python 3.9
  .github/workflows/unittest.yml
  README.md
Labels: documentation

#662 :arrow_up: 0.12.0
  setup.py
Labels: skip-changelog

#674 Update CI to TF 2.5.0 stable
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
Labels: internal-improvement
