Repository larq/larq, pull requests merged in 2021-02, with the labels that each got.

#614 Support 1d ops in model profile
  larq/models.py
  larq/models_test.py
Labels: bug

#618 :arrow_up: 0.10.3
  setup.py
Labels: skip-changelog

#621 Call super().build() in Quantizers.build()
  larq/quantizers.py
Labels: bug

#622 Build flip_ratio metric in Layer.build
  larq/quantizers.py
Labels: internal-improvement

#623 Add public base class for defining quantizers and hide BaseQuantizer
  larq/quantizers.py
Labels: breaking-change

#625 :arrow_up: 0.11.0
  setup.py
Labels: skip-changelog

#626 Favour lq.quantizers.NoOp over NoOpQuantizer
  larq/layers_base.py
  larq/quantizers.py
Labels: internal-improvement

#627 Rename Quantizer type to prevent conflict with base class
  larq/layers_base.py
  larq/quantized_variable.py
  larq/quantizers.py
Labels: bug

#628 :arrow_up: 0.11.1
  setup.py
Labels: bug

#629 Initialise CaseOptimizer.iterations which is required in TF 2.3+
  larq/optimizers.py
Labels: bug

#630 :arrow_up: 0.11.2
  setup.py
Labels: skip-changelog
